version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cache
      - /etc/localtime:/etc/localtime:ro
      - home:/home/ubuntu

    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  home:
