"$schema" = 'https://starship.rs/config-schema.json'

format = "$username[@](bold white)$hostname[: ](bold white)$directory$all$line_break$character"

palette = "catppuccin_mocha"

[container]
disabled = true

[cmd_duration]
min_time = 1_000
show_milliseconds = true

[hostname]
format = '[$hostname]($style)'
ssh_only = false

[username]
format = "[$user]($style)"
show_always = true

[git_metrics]
disabled = false

[kubernetes]
detect_folders = ['k8s', 'kubernetes']
format = 'for [$symbol$context( \($namespace\))]($style) '
disabled = false

[git_commit]
tag_disabled = false

[git_status]
deleted = "x"

[c]
detect_folders = ["include"]

[directory]
truncate_to_repo = false
truncation_length = -1

[status]
disabled = false
symbol = "[x](bold red) "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
